### ISSUE TITLE
Error: Unsupported interlace method

### ISSUE THREAD

**Issue by iazrael** [niegowski/node-pngjs#12]
fs.createReadStream('/data/test/test.png').pipe(new PNG())
    .on('parsed', function() {
        //...
    })
    .on('error', function(e){
        // I get an "Unsupported interlace method" error.
    });

What  happen?

**Comment by lukeapage** [comment]
@iazrael I have forked and implemented
https://www.npmjs.com/package/pngjs2

**Comment by iazrael** [comment]
Good job, let me have a try.
