### ISSUE TITLE
Export without import

### ISSUE THREAD

**Issue by 26medias** [niegowski/node-pngjs#20]
Hi,

Is it possible to simply export a PNG if I have the values generated by code, instead of being a modification of an exiting PNG.

I can't find how to do that.

Thanks.

**Comment by marcelerz** [comment]
You can do the following:
```
// Create image of size 320, 200
var image = new PNG({
		width: 320,
		height: 200
	});
```
Then you can modify the ```data``` of the ```image``` as if you have loaded it from a file.

**Comment by 26medias** [comment]
Thanks. It worked.

If people search for the code in the future:

	var image = new PNG({
		width:	this.options.width,
		height:	this.options.height
	});
	var writeStream = fs.createWriteStream(filename);
	image.pack().pipe(writeStream);
	writeStream.on('finish', function() {
		console.log("Image saved.");
	});
	writeStream.on('error', function (err) {
		console.error(err);
	});
